#define	C_LOCATEDBF		"请定位源数据表："
#define	C_OUTPUT		"源数据表与目的数据表不能同名。"
#define	C_NEED3FLDS		"交叉表的源数据表至少需要三个字段"
#define	C_EMPTYDBF		"无法在空数据表上准备交叉表"
#define	C_BADPAGEFLD	"源数据表中的交叉表页字段类型不能是备注、通用或图片。"
#define	C_BADROWFLD		"源数据表中的交叉表行字段类型不能是备注、通用或图片。"
#define	C_BADCOLFLD		"源数据表中的交叉表列字段类型不能是备注、通用或图片。"
#define	C_BADCELLFLD	"源数据表中的交叉表单元格字段类型不能是备注、通用或图片。"
#define	C_NOCOLS		"没有找到列。"
#define	C_XSVALUES		"列字段不能超过 254 个。"
#define	C_UNKNOWNFLD	"未知的字段类型。"
